### ISSUE TITLE
Better input validation

### ISSUE THREAD

**Issue by silascutler** [xillwillx/skiptracer#1]
Some variable like `fname` in `truthfinder.py` are contingent upon user input containing a space.  These should be checked / parsed to ensure a user enters data in the correct format:

```
Traceback (most recent call last):
  File "skiptracer.py", line 95, in <module>
    main()
  File "/home/XXXXXXXXXXXXX/.local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/XXXXXXXXXXXXX/.local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/XXXXXXXXXXXXX/.local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/XXXXXXXXXXXXX/.local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "skiptracer.py", line 73, in main
    TruthFinderGrabber().get_info(lookup,search_string)
  File "/home/XXXXXXXXXXXXX/skiptracer/plugins/truthfinder.py", line 171, in get_info
    self.truth_try(lookup,information)  # Actual logic to run + re-try request
  File "/home/XXXXXXXXXXXXX/skiptracer/plugins/truthfinder.py", line 97, in truth_try
    self.url = "https://www.truthfinder.com/results/?utm_source=VOTER&traffic%5Bsource%5D=VOTER&utm_medium=pre-pop&traffic%5Bmedium%5D=pre-pop&utm_campaign=&traffic%5Bcampaign%5D=srapi%3A&utm_term=1&traffic%5Bterm%5D=1&utm_content=&traffic%5Bcontent%5D=&s1=&s2=srapi&s3=1&s4=&s5=&city=&firstName={}&lastName={}&page=r&state={}{}&qLocation=true&qRelatives=true&qOver30={}".format(self.fname, self.lname, self.state, self.gndr, self.age)
AttributeError: TruthFinderGrabber instance has no attribute 'fname'
```

(Nice work on the project :+1: )

**Comment by xillwillx** [comment]
will fix as soon as I get back from Hushcon
