### ISSUE TITLE
Frequent problems with Pip in installation

### ISSUE THREAD

**Issue by Z33DD** [xillwillx/skiptracer#20]
# Frequent problems with Pip in installation

## If this command don't works

``` bash
pip install -r requirements.txt
```
## Try

``` bash
pip install -r requirements.txt --user
```
This will solve the permissions' problem
```
Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/pip'
Consider using the `--user` option or check the permissions.
```

## If you continues to have problems with pip, [try reinstall](https://stackoverflow.com/questions/49940813/pip-no-module-named-internal)
``` bash
curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
python2.7 get-pip.py --force-reinstall --user
rm get-pip.py
python -m pip install --upgrade pip --user
```

### for example
```bash
$ python skiptracer.py
Traceback (most recent call last):
  File "skiptracer.py", line 4, in <module>
    from plugins.menus import menus
  File "/home/user/Programs/skiptracer/plugins/menus.py", line 12, in <module>
    from plugins.haveibeenpwned import HaveIBeenPwwnedGrabber
  File "/home/user/Programs/skiptracer/plugins/haveibeenpwned.py", line 9, in <module>
    import simplejson as json
ImportError: No module named simplejson
```
### So try 
```bash
pip install simplejson --user
```

### Input
``` bash
pip install -r requirements.txt
``` 
### Output
``` bash
Command "/usr/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-3vKgda/python-docx/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-psEbaD/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-3vKgda/python-docx/
```

### When I try install manually
``` bash
$ pip install docx --user
/home/user/.local/lib/python2.7/site-packages/pip/_vendor/requests/__init__.py:83: RequestsDependencyWarning: Old version of cryptography ([1, 2, 3]) may cause slowdown.
  warnings.warn(warning, RequestsDependencyWarning)
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Requirement already satisfied: docx in /home/user/.local/lib/python2.7/site-packages (0.2.4)
Requirement already satisfied: Pillow>=2.0 in /home/user/.local/lib/python2.7/site-packages (from docx) (5.4.1)
Requirement already satisfied: lxml in /usr/lib/python2.7/dist-packages (from docx) (3.5.0)
```
### The error continues
``` bash
$ python skiptracer.py
Traceback (most recent call last):
  File "skiptracer.py", line 4, in <module>
    from plugins.menus import menus
  File "/home/z33dd/Programs/skiptracer/plugins/menus.py", line 19, in <module>
    from plugins.reporter import ReportGenerator
  File "/home/z33dd/Programs/skiptracer/plugins/reporter.py", line 1, in <module>
    from docx import Document
ImportError: cannot import name Document
```

**Comment by rpigu-i** [comment]
Hey there. Please refer to the Python 3.x branch. This is being actively worked on, and will resolve installation issues including providing a variety of installation options (Docker, pypi, requirements.txt etc.).
