### ISSUE TITLE
Error "No module named '__builtin__'"

### ISSUE THREAD

**Issue by LanceLake** [xillwillx/skiptracer#22]
Did the requirements install. Got the following error message.

No module named '__builtin__'
Traceback (most recent call last):
  File "skiptracer.py", line 4, in <module>
    from plugins.menus import menus
  File "C:\Users\Joseph\Desktop\skiptracer-master\plugins\menus.py", line 13, in <module>
    from plugins.namechk2 import NameChkGrabber
  File "C:\Users\Joseph\Desktop\skiptracer-master\plugins\namechk2.py", line 12, in <module>
    from urllib import urlencode
ImportError: cannot import name 'urlencode' from 'urllib' (C:\Users\Joseph\AppData\Local\Programs\Python\Python37-32\lib\urllib\__init__.py)

So I try the code to install builtin (pip), but that errors out as well.

**Comment by nadav-rahimi** [comment]
in skiptracer-master\plugins\namechk2.py you need to change `from urllib import urlencode` to `from urllib.parse import urlencode` since the old one is for python2 and the new line is for python3

after fixing this error however I seem to get an error:
`(skiptracer) C:\Users\nadav\Documents\Nadav\Coding\GitHub Projects\skiptracer>python skiptracer.py
No module named '__builtin__'
Traceback (most recent call last):
  File "skiptracer.py", line 4, in <module>
    from plugins.menus import menus
  File "C:\Users\nadav\Documents\Nadav\Coding\GitHub Projects\skiptracer\plugins\menus.py", line 16, in <module>
    from plugins.knowem import KnowemGrabber
  File "C:\Users\nadav\Documents\Nadav\Coding\GitHub Projects\skiptracer\plugins\knowem.py", line 8, in <module>
    from colors import BodyColors as bc
ModuleNotFoundError: No module named 'colors'`

hopefully this helps

**Comment by rpigu-i** [comment]
@LanceLake Please refer to the Python 3.x branch going forward. It's not complete yet, but the builtin module issue will be resolved there.

Thanks.
