### ISSUE TITLE
Error Message Line4, Line 5, 8, 314, 70

### ISSUE THREAD

**Issue by jmcquiggan** [xillwillx/skiptracer#23]
Using the Buscador VM with Skiptracer, getting the following message when starting (deleted the folder and did a PIP install with the requirements.

Traceback (most recent call last):
  File "skiptracer.py", line 4, in <module>
    from plugins.menus import menus
  File "/opt/skiptracer/plugins/menus.py", line 5, in <module>
    from plugins.fouroneone_info import FourOneOneGrabber
  File "/opt/skiptracer/plugins/fouroneone_info.py", line 5, in <module>
    from plugins.base import PageGrabber
  File "/opt/skiptracer/plugins/base.py", line 8, in <module>
    from bs4 import BeautifulSoup
  File "/usr/local/lib/python2.7/dist-packages/bs4/__init__.py", line 30, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "/usr/local/lib/python2.7/dist-packages/bs4/builder/__init__.py", line 314, in <module>
    from . import _html5lib
  File "/usr/local/lib/python2.7/dist-packages/bs4/builder/_html5lib.py", line 70, in <module>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
AttributeError: 'module' object has no attribute '_base'

**Comment by LanceLake** [comment]
Also getting this error which is probably related.

C:\Users\Joseph\Desktop\Applications\skiptracer-master>python skiptracer.py
Traceback (most recent call last):
  File "skiptracer.py", line 4, in <module>
    from plugins.menus import menus
  File "C:\Users\Joseph\Desktop\Applications\skiptracer-master\plugins\menus.py", line 5, in <module>
    from plugins.fouroneone_info import FourOneOneGrabber
  File "C:\Users\Joseph\Desktop\Applications\skiptracer-master\plugins\fouroneone_info.py", line 5, in <module>
    from plugins.base import PageGrabber
  File "C:\Users\Joseph\Desktop\Applications\skiptracer-master\plugins\base.py", line 4, in <module>
    import requests
ImportError: No module named requests

**Comment by DrPolaroid** [comment]
I'm having the exact same issue. Any updates here?

**Comment by rpigu-i** [comment]
Hey everyone. The Python 3.x branch is being actively worked on by a variety of individuals, to upgrade the code base and fix errors. Please refer to this branch and feel free to create PR's for any fixes. Thanks

**Comment by aditya-9898** [comment]
Can anyone help to intall skiptracer without any error .. please solve the issues like module not found or import FourOneOneGrabber
