### ISSUE TITLE
no module named requests

### ISSUE THREAD

**Issue by sk3lk0** [xillwillx/skiptracer#31]
skel@skel:~/Downloads/git/skiptracer$ python skiptracer.py 
Traceback (most recent call last):
  File "skiptracer.py", line 4, in <module>
    from plugins.menus import menus
  File "/home/skel/Downloads/git/skiptracer/plugins/menus.py", line 5, in <module>
    from plugins.fouroneone_info import FourOneOneGrabber
  File "/home/skel/Downloads/git/skiptracer/plugins/fouroneone_info.py", line 5, in <module>
    from plugins.base import PageGrabber
  File "/home/skel/Downloads/git/skiptracer/plugins/base.py", line 4, in <module>
    import requests
ImportError: No module named requests
but module requests is installed

**Comment by rpigu-i** [comment]
Please see the Python 3.x branch. Active development and bug fixes are taking place there.

Thanks.
