### ISSUE TITLE
2 Errors I'm seeing

### ISSUE THREAD

**Issue by Jsimpki** [xillwillx/skiptracer#50]
I'm a journalist and I'm used to having to skiptrace by hand. This is the first time using this particular program and I'm running to issues into the install. I'm running Parrot Security OS, and I have python 2.7 and Python3.3 onboard already. I'm already working on the final error on #1 with pip upgrade but I cant get python to run as py3.3 without having to call it directly. Could you look into this and see if you can reproduce and come up with a solution, especially to the missing module.

1. _$sudo pip install -r requirements.txt_ 
**DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting python-docx
  Using cached python-docx-0.8.10.tar.gz (5.5 MB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-QBwFCV/python-docx/setup.py'"'"'; __file__='"'"'/tmp/pip-install-QBwFCV/python-docx/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-QBwFCV/python-docx/pip-egg-info
         cwd: /tmp/pip-install-QBwFCV/python-docx/
    Complete output (3 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ImportError: No module named setuptools
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.**

2. _$python3 skiptracer.py_
**No module named '__builtin__'
Traceback (most recent call last):
  File "skiptracer.py", line 4, in <module>
    from plugins.menus import menus
  File "/home/pl46u3/Desktop/skiptracer/plugins/menus.py", line 12, in <module>
    from plugins.haveibeenpwned import HaveIBeenPwwnedGrabber
  File "/home/pl46u3/Desktop/skiptracer/plugins/haveibeenpwned.py", line 13, in <module>
    import cfscrape
ModuleNotFoundError: No module named 'cfscrape'**

**Comment by Jsimpki** [comment]
_Wait I got a solution for the issue of cfscrape and the error I was getting with setup tools. 
Use commands **pip install setuptools && git clone https://github.com/Anorov/cloudflare-scrape.git && cd skiptracer && pip install -r skiptracer** _

**Comment by AlecMcCutcheon** [comment]
Even if you manage to get the script running it's not going to work Correctly Most of the stuff in it is broken because it has not been updated to python 3 yet Trust me I've spent hours trying to get it to work  Just have to patiently wait for it to be updated

**Comment by AlecMcCutcheon** [comment]
On top of that some of the API that was being used in that script is no longer supported and needs to be updated as well

**Comment by AlecMcCutcheon** [comment]
The creator should tell people that it is broken so they don't spend all that time trying to get it to work.

**Comment by Alexandros-Kordatzakis** [comment]
Same thing happened to me. He mentions that he is updating to Python 3, but never mentions that nothing works.

**Comment by AlecMcCutcheon** [comment]
I even went as far as trying to convert the entire thing to python 3 myself using 2to3  As like I said before I figured out that the API's were out of date

**Comment by AlecMcCutcheon** [comment]
I was able to get the script to run on windows 10 linux WSL But obviously it's broken so it's not going to work at the moment But it's still cool that once it is updated it should still be able to be run on windows 10

**Comment by Alexandros-Kordatzakis** [comment]
As he said, no issues will be taken in mind...
