### ISSUE TITLE
Several issues with importing twitter and color module.

### ISSUE THREAD

**Issue by pipoweruser2019** [xillwillx/skiptracer#6]
There seem to be some inconsistencies for how printing works, might be a mix up of py2 and 3. Also it has issues importing the color module. I tried to make changes but it might just be my set up. Would love to contribute otherwise.

**Comment by xillwillx** [comment]
if you would like to suggest some edits, post here, we are working on version 2.0 currently, some of the edits will be incorporated if not already fixed

**Comment by bassreaves** [comment]
Seeing the below message after running skiptracer.py

Traceback (most recent call last):
  File "skiptracer.py", line 6, in <module>
    from plugins.twitter import TwitterGrabber
  File "C:\Users\******\Documents\GitHub\skiptracer\plugins\twitter.py", line 76
    print "\n  [+]", "-" *80
                  ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("\n  [+]", "-" *80)?

**Comment by cWjL** [comment]
When using the TruePeopleSearch and AdvanceBackgroundChecks plugins:

```
[?] TruePeopleSearch
  [!] Please enter an age range, ex: 18-120 30-40
  [!] Please enter a city,state,or zip - ex: (AL|Alabama|12345) AZ
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:845: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)

unorderable types: Tag() < Tag()

[?] AdvanceBackgroundChecks
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:845: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
```
