### ISSUE TITLE
lxml error

### ISSUE THREAD

**Issue by Om3gaa** [xillwillx/skiptracer#65]
when i run skiptracer.py i get this:

Traceback (most recent call last):
  File "skiptracer.py", line 4, in <module>
    import plugins.proxygrabber as pg
  File "C:\Users\maxen\OneDrive\Documents\maison\1Maxence\skiptracer-master\plugins\proxygrabber.py", line 4, in <module>
    from lxml.html import fromstring
ImportError: No module named lxml.html

**Comment by InfoSecGeoff** [comment]
have you installed the dependencies from the requirements.txt yet? that was not enough to get it working, i found i had to manually install lxml with the following:
sudo apt-get install python3-lxml
sudo apt-get install libxml2-dev libxslt-dev python-dev

**Comment by kikokimo1** [comment]
> have you installed the dependencies from the requirements.txt yet? that was not enough to get it working, i found i had to manually install lxml with the following: sudo apt-get install python3-lxml sudo apt-get install libxml2-dev libxslt-dev python-dev

i got the same error as Om3gaa, i did what you've suggested, (sudo apt-get install python3-lxml and sudo apt-get install libxml2-dev libxslt-dev python-dev) and i got the same error when i tried running skiptracer.py 

also if you didn't know this program uses python 2.7 so i went from python3 to python-2.7 and it still gave me an error
