### ISSUE TITLE
plugins.menus

### ISSUE THREAD

**Issue by shadow526** [xillwillx/skiptracer#69]
I've been getting this issue for the past couple of days can anyone fix it.
Traceback (most recent call last):
  File "skiptracer.py", line 4, in <module>
    from plugins.menus import menus
ImportError: No module named plugins.menus

**Comment by Shaheertura** [comment]
ive got the same problem

**Comment by network-knight** [comment]
i have faced the same problem

**Comment by lordgauvin** [comment]
I have the same problem. Is there already a  solution?

**Comment by Fuse8499** [comment]
what a pos script

**Comment by phoenix4147** [comment]
> I've been getting this issue for the past couple of days can anyone fix it. Traceback (most recent call last): File "skiptracer.py", line 4, in from plugins.menus import menus ImportError: No module named plugins.menus

me too..

**Comment by odi700** [comment]
I have the same problem is there a solution for it?
